### ISSUE TITLE
[Debug] Album page title bug

### ISSUE THREAD

**Issue by jeongahn** [kookmin-sw/capstone-2024-13#124]
> ### ISSUE
> * Type: 'Debug'
> * Detail: Album page title bug

title 길이에 대한 전처리가 없어서 보이는 bug입니다.
아래는 해당 문제와 Recommend입니다.
1. 한 줄 text length limit  : <= 26
![image](https://github.com/kookmin-sw/capstone-2024-13/assets/54920329/371bdaa8-13a6-45f9-9f6e-962f2ad9ba96)
![image](https://github.com/kookmin-sw/capstone-2024-13/assets/54920329/f090d9b3-eab4-4618-a642-1089a81dfcc4)

2. maximum row length <= 2
![image](https://github.com/kookmin-sw/capstone-2024-13/assets/54920329/6d151042-6d1f-4d39-a81c-563bc6cd9398)

TODO
> - [x]  한 줄 최대 text length 수정
> - [ ]  최대 text 들여쓰기 허용 범위 수정

### mention
@younganswer @yoon2000

**Comment by younganswer** [comment]
네 감사합니다 처리하도록 하겠습니다
