### ISSUE TITLE
[Secure] IDOR Vulnerability report

### ISSUE THREAD

**Issue by jeongahn** [kookmin-sw/capstone-2024-13#135]
> ### ISSUE
> * Type: `Secure'
> * Detail: IDOR 취약점 발견 및 버그 리포트
> 
> ### TODO
> 1.  [ ]  Private diary를 임의로 접근할 수 있는 문제 수정
> 2.  [ ]  Objectid를 유추할 수 있는 문제 수정
>
> 자세한 내용은 취약점 평가 보고서를 참조해주세요
>
> report link : https://drive.google.com/file/d/1rxFvBVz0RtUXyp-HGbKgNcsVRMEgMcD0/view?usp=sharing

@yoon2000 @younganswer

**Comment by younganswer** [comment]
확인했습니다. 수정하고 PR 올리도록 하겠습니다.

**Comment by yoon2000** [comment]
확인했습니다
