### ISSUE TITLE
[Fix] User, Diary Schema 구조 설계 및 수정

### ISSUE THREAD

**Issue by yoon2000** [kookmin-sw/capstone-2024-13#18]
> ### ISSUE
> * Type: `Fix`
> * Detail: Fix schema
> 
> ### TODO
> 1. [x]  Diary랑 User schema 부모 참조형식으로 바꾸기
>

[참고 사이트]
https://www.mongodb.com/developer/products/mongodb/mongodb-schema-design-best-practices/

### embeded 방식
```json:user.json
{
	"_id" : "ObjectId('fjdlfjaslkfj')",
	"createdAt": ISODate("2024-03-09T12:42:41.382Z"),
	"email" : "younganser@kookmin.ac.kr",
	"nickname" : "younganswer",
	"profileImageUrl": "cmkls1dmlav13r55";
	"diaries" : [ ObjectID('dfasfsas'), ObjectID('cvmzxlpzxv'), ... ]
}
```

위와같이 임베딩 방식으로 schema를 짜게되면 단일쿼리에 모든 정보를 조회 할 수 있지만, [MongoDB의 16MB 문서 크기 제한](https://docs.mongodb.com/manual/reference/limits/) 즉 MongoDB의 문서 크기 제한될 가능성이 있다.

### One-to-Squillions - 부모 참조 방식

```json:user.json
{
	"_id" : "ObjectId('fjdlfjaslkfj')",
	"createdAt": ISODate("2024-03-09T12:42:41.382Z"),
	"email" : "younganser@kookmin.ac.kr",
	"nickname" : "younganswer",
	"profileImageUrl": "cmkls1dmlav13r55";
}
```

```json:Diary.json
{
	"_id": "ObjectId('328492489')",
	"userId": "ObjectId('fjdlfjaslkfj')", // 부모의 obj id 를 참조
	"createdAt": ISODate("2024-03-09T12:42:41.382Z"),
	"title":"평범한 일상"
	"content":"피곤해"
}
```

따라서 문서 크기 제한을 피하기 위해서 User에서 Diary를 참조하는 방식이 아니라 Diary에서 User를 참조하는 부모 참조 형식으로 Schema 구조를 디자인 해야한다.

**Comment by younganswer** [comment]
이해했습니다 감사합니다
